[package]
name = "variable"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", optional = true, default-features = false, features = [ "alloc" ] }

[features]
default = ["std", "serde"]

# enable std library
std = [ "serde?/std" ]
